import "server-only";
import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

/**
 * Private storage for donation e-Slips.
 *
 * - Production: a PRIVATE Supabase Storage bucket, accessed only with the server-side
 *   service-role key. Files are never public; admins get short-lived signed URLs.
 * - Development without Supabase credentials (or SLIP_STORAGE=local): files go to
 *   `.data/slips/` on local disk (git-ignored) so the donation flow can be exercised end to end.
 */

const SLIP_BUCKET = process.env.SUPABASE_SLIP_BUCKET || "slips";
const LOCAL_ROOT = path.join(process.cwd(), ".data", "slips");

let supabase: SupabaseClient | null | undefined;

function getSupabase(): SupabaseClient | null {
  if (supabase !== undefined) return supabase;
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (url && key) {
    supabase = createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } });
  } else if (process.env.NODE_ENV === "production" && process.env.SLIP_STORAGE !== "local") {
    // Refuse to silently write donor slips to an ephemeral server disk.
    throw new Error("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or SLIP_STORAGE=local for a single-server deploy).");
  } else {
    supabase = null;
  }
  return supabase;
}

const EXTENSIONS = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp" } as const;
export type SlipMimeType = keyof typeof EXTENSIONS;

/**
 * Detect the real image type from the file's magic bytes — the browser-supplied
 * MIME type is attacker-controlled and must not be trusted on its own.
 */
export function sniffImageType(bytes: Uint8Array): SlipMimeType | null {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg";
  if (
    bytes.length >= 8 &&
    [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a].every((b, i) => bytes[i] === b)
  ) {
    return "image/png";
  }
  if (
    bytes.length >= 12 &&
    String.fromCharCode(...bytes.subarray(0, 4)) === "RIFF" &&
    String.fromCharCode(...bytes.subarray(8, 12)) === "WEBP"
  ) {
    return "image/webp";
  }
  return null;
}

/** Store a slip and return its storage key, e.g. `2026/10/3f0c…e1.jpg`. */
export async function uploadSlip(bytes: Uint8Array, contentType: SlipMimeType): Promise<string> {
  const now = new Date();
  const key = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, "0")}/${randomUUID()}.${EXTENSIONS[contentType]}`;

  const client = getSupabase();
  if (client) {
    const { error } = await client.storage.from(SLIP_BUCKET).upload(key, bytes, { contentType, upsert: false });
    if (error) throw new Error(`Slip upload failed: ${error.message}`);
  } else {
    const file = path.join(LOCAL_ROOT, key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, bytes);
  }
  return key;
}

export async function deleteSlip(key: string): Promise<void> {
  const client = getSupabase();
  if (client) {
    await client.storage.from(SLIP_BUCKET).remove([key]);
  } else {
    await rm(localPath(key), { force: true });
  }
}

/**
 * Short-lived URL for an admin to view a slip. Returns `null` in local development,
 * where slips are served through the authenticated admin route instead (step 6).
 */
export async function getSlipSignedUrl(key: string, expiresInSeconds = 300): Promise<string | null> {
  const client = getSupabase();
  if (!client) return null;
  const { data, error } = await client.storage.from(SLIP_BUCKET).createSignedUrl(key, expiresInSeconds);
  if (error) throw new Error(`Could not sign slip URL: ${error.message}`);
  return data.signedUrl;
}

/** Local-development only: read a slip from disk. */
export async function readLocalSlip(key: string): Promise<Buffer> {
  return readFile(localPath(key));
}

function localPath(key: string) {
  // Keys are generated by uploadSlip; still refuse anything that escapes the slip root.
  const file = path.resolve(LOCAL_ROOT, key);
  if (!file.startsWith(LOCAL_ROOT + path.sep)) throw new Error("Invalid slip key");
  return file;
}
